### ISSUE TITLE
cannot torch.compile the HunyuanVideo video transformer

### ISSUE THREAD

**Issue by alexarmbr** [chengzeyi/ParaAttention#22]
First of all thanks Zeyi for the awesome implementation! I am trying to torch.compile HunyuanVideo's transformer module, using code very similiar to what is [here](https://github.com/chengzeyi/ParaAttention/blob/main/doc/fastest_hunyuan_video.md#parallelize-the-inference-with-context-parallelism)

## Code

```python
import time
import torch
import torch.distributed as dist
from diffusers import HunyuanVideoPipeline, HunyuanVideoTransformer3DModel
from diffusers.utils import export_to_video

dist.init_process_group()

torch.cuda.set_device(dist.get_rank())

# [rank1]: RuntimeError: Expected mha_graph->execute(handle, variant_pack, workspace_ptr.get()).is_good() to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
torch.backends.cuda.enable_cudnn_sdp(False)

model_id = "checkpoints"
transformer = HunyuanVideoTransformer3DModel.from_pretrained(
    model_id,
    subfolder="transformer",
    torch_dtype=torch.bfloat16,
    revision="refs/pr/18",
)
pipe = HunyuanVideoPipeline.from_pretrained(
    model_id,
    transformer=transformer,
    torch_dtype=torch.float16,
    revision="refs/pr/18",
).to("cuda")

from para_attn.context_parallel import init_context_parallel_mesh
from para_attn.context_parallel.diffusers_adapters import parallelize_pipe
from para_attn.parallel_vae.diffusers_adapters import parallelize_vae

mesh = init_context_parallel_mesh(
    pipe.device.type,
)
parallelize_pipe(
    pipe,
    mesh=mesh,
)

pipe.transformer = torch.compile(
   pipe.transformer, mode="max-autotune-no-cudagraphs",
)

for i in range(2):
    begin = time.time()
    output = pipe(
        prompt="A cat walks on the grass, realistic",
        height=720,
        width=1280,
        num_frames=129,
        num_inference_steps=1 if i == 0 else 30,
        output_type="pil" if dist.get_rank() == 0 else "pt",
    ).frames[0]
    end = time.time()
    if dist.get_rank() == 0:
        if i == 0:
            print(f"Warm up time: {end - begin:.2f}s")
        else:
            print(f"Time: {end - begin:.2f}s")

if dist.get_rank() == 0:
    print("Saving video to hunyuan_video.mp4")
    export_to_video(output, "hunyuan_video.mp4", fps=15)

dist.destroy_process_group()
```
When I run this code with `torchrun --nproc-per-node 4 hunyuan_compile.py` I get the following error:

## Error
```
root@743451327c16:/workspaces/cog-hunyuanvideo-multigpu# CUDA_VISIBLE_DEVICES=4,5,6,7 torchrun --nproc-per-node 4 hunyuan_compile.py 
W0129 01:38:03.717000 84694 site-packages/torch/distributed/run.py:793] 
W0129 01:38:03.717000 84694 site-packages/torch/distributed/run.py:793] *****************************************
W0129 01:38:03.717000 84694 site-packages/torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0129 01:38:03.717000 84694 site-packages/torch/distributed/run.py:793] *****************************************
Loading pipeline components...:   0%|                                                                                                                                                                  | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 11.46it/s]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 11.35it/s]
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  3.72it/s]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 11.47it/s]
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  3.66it/s]
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  3.63it/s]
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  3.60it/s]
  0%|                                                                                                                                                                                                  | 0/1 [00:00<?, ?it/s][rank0]:W0129 01:38:51.588000 84769 site-packages/torch/_dynamo/convert_frame.py:844] [2/8] torch._dynamo hit config.cache_size_limit (8)
[rank0]:W0129 01:38:51.588000 84769 site-packages/torch/_dynamo/convert_frame.py:844] [2/8]    function: 'forward' (/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/transformers/transformer_hunyuan_video.py:463)
[rank0]:W0129 01:38:51.588000 84769 site-packages/torch/_dynamo/convert_frame.py:844] [2/8]    last reason: 2/0: ___check_obj_id(L['self']._modules['attn'].processor, 140211356151952)
[rank0]:W0129 01:38:51.588000 84769 site-packages/torch/_dynamo/convert_frame.py:844] [2/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
[rank0]:W0129 01:38:51.588000 84769 site-packages/torch/_dynamo/convert_frame.py:844] [2/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
[rank2]:W0129 01:38:51.588000 84771 site-packages/torch/_dynamo/convert_frame.py:844] [2/8] torch._dynamo hit config.cache_size_limit (8)
[rank2]:W0129 01:38:51.588000 84771 site-packages/torch/_dynamo/convert_frame.py:844] [2/8]    function: 'forward' (/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/transformers/transformer_hunyuan_video.py:463)
[rank2]:W0129 01:38:51.588000 84771 site-packages/torch/_dynamo/convert_frame.py:844] [2/8]    last reason: 2/0: ___check_obj_id(L['self']._modules['attn'].processor, 140318667175440)
[rank2]:W0129 01:38:51.588000 84771 site-packages/torch/_dynamo/convert_frame.py:844] [2/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
[rank2]:W0129 01:38:51.588000 84771 site-packages/torch/_dynamo/convert_frame.py:844] [2/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
[rank3]:W0129 01:38:51.588000 84772 site-packages/torch/_dynamo/convert_frame.py:844] [2/8] torch._dynamo hit config.cache_size_limit (8)
[rank3]:W0129 01:38:51.588000 84772 site-packages/torch/_dynamo/convert_frame.py:844] [2/8]    function: 'forward' (/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/transformers/transformer_hunyuan_video.py:463)
[rank3]:W0129 01:38:51.588000 84772 site-packages/torch/_dynamo/convert_frame.py:844] [2/8]    last reason: 2/0: ___check_obj_id(L['self']._modules['attn'].processor, 140376578963472)
[rank3]:W0129 01:38:51.588000 84772 site-packages/torch/_dynamo/convert_frame.py:844] [2/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
[rank3]:W0129 01:38:51.588000 84772 site-packages/torch/_dynamo/convert_frame.py:844] [2/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
[rank1]:W0129 01:38:51.588000 84770 site-packages/torch/_dynamo/convert_frame.py:844] [2/8] torch._dynamo hit config.cache_size_limit (8)
[rank1]:W0129 01:38:51.588000 84770 site-packages/torch/_dynamo/convert_frame.py:844] [2/8]    function: 'forward' (/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/transformers/transformer_hunyuan_video.py:463)
[rank1]:W0129 01:38:51.588000 84770 site-packages/torch/_dynamo/convert_frame.py:844] [2/8]    last reason: 2/0: ___check_obj_id(L['self']._modules['attn'].processor, 140328729670800)
[rank1]:W0129 01:38:51.588000 84770 site-packages/torch/_dynamo/convert_frame.py:844] [2/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
[rank1]:W0129 01:38:51.588000 84770 site-packages/torch/_dynamo/convert_frame.py:844] [2/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
[rank3]:W0129 01:38:58.442000 84772 site-packages/torch/_dynamo/convert_frame.py:844] [5/8] torch._dynamo hit config.cache_size_limit (8)
[rank3]:W0129 01:38:58.442000 84772 site-packages/torch/_dynamo/convert_frame.py:844] [5/8]    function: 'forward' (/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/transformers/transformer_hunyuan_video.py:385)
[rank3]:W0129 01:38:58.442000 84772 site-packages/torch/_dynamo/convert_frame.py:844] [5/8]    last reason: 5/0: ___check_obj_id(L['self']._modules['attn'].processor, 140376578699216)
[rank3]:W0129 01:38:58.442000 84772 site-packages/torch/_dynamo/convert_frame.py:844] [5/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
[rank3]:W0129 01:38:58.442000 84772 site-packages/torch/_dynamo/convert_frame.py:844] [5/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
[rank0]:W0129 01:38:58.442000 84769 site-packages/torch/_dynamo/convert_frame.py:844] [5/8] torch._dynamo hit config.cache_size_limit (8)
[rank0]:W0129 01:38:58.442000 84769 site-packages/torch/_dynamo/convert_frame.py:844] [5/8]    function: 'forward' (/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/transformers/transformer_hunyuan_video.py:385)
[rank0]:W0129 01:38:58.442000 84769 site-packages/torch/_dynamo/convert_frame.py:844] [5/8]    last reason: 5/0: ___check_obj_id(L['self']._modules['attn'].processor, 140211399792848)
[rank0]:W0129 01:38:58.442000 84769 site-packages/torch/_dynamo/convert_frame.py:844] [5/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
[rank0]:W0129 01:38:58.442000 84769 site-packages/torch/_dynamo/convert_frame.py:844] [5/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
[rank2]:W0129 01:38:58.442000 84771 site-packages/torch/_dynamo/convert_frame.py:844] [5/8] torch._dynamo hit config.cache_size_limit (8)
[rank2]:W0129 01:38:58.442000 84771 site-packages/torch/_dynamo/convert_frame.py:844] [5/8]    function: 'forward' (/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/transformers/transformer_hunyuan_video.py:385)
[rank2]:W0129 01:38:58.442000 84771 site-packages/torch/_dynamo/convert_frame.py:844] [5/8]    last reason: 5/0: ___check_obj_id(L['self']._modules['attn'].processor, 140318666943376)
[rank2]:W0129 01:38:58.442000 84771 site-packages/torch/_dynamo/convert_frame.py:844] [5/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
[rank2]:W0129 01:38:58.442000 84771 site-packages/torch/_dynamo/convert_frame.py:844] [5/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
[rank1]:W0129 01:38:58.442000 84770 site-packages/torch/_dynamo/convert_frame.py:844] [5/8] torch._dynamo hit config.cache_size_limit (8)
[rank1]:W0129 01:38:58.442000 84770 site-packages/torch/_dynamo/convert_frame.py:844] [5/8]    function: 'forward' (/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/transformers/transformer_hunyuan_video.py:385)
[rank1]:W0129 01:38:58.442000 84770 site-packages/torch/_dynamo/convert_frame.py:844] [5/8]    last reason: 5/0: ___check_obj_id(L['self']._modules['attn'].processor, 140328729284432)
[rank1]:W0129 01:38:58.442000 84770 site-packages/torch/_dynamo/convert_frame.py:844] [5/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
[rank1]:W0129 01:38:58.442000 84770 site-packages/torch/_dynamo/convert_frame.py:844] [5/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:27<00:00, 27.05s/it]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:27<00:00, 27.00s/it]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:27<00:00, 27.00s/it]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:27<00:00, 27.01s/it]
[rank1]: Traceback (most recent call last):
[rank1]:   File "/workspaces/cog-hunyuanvideo-multigpu/hunyuan_compile.py", line 46, in <module>
[rank1]:     output = pipe(
[rank1]:              ^^^^^
[rank1]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/para_attn/context_parallel/diffusers_adapters/hunyuan_video.py", line 204, in new_call
[rank1]:     return original_call(self, *args, generator=generator, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank1]:     return func(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/pipelines/hunyuan_video/pipeline_hunyuan_video.py", line 676, in __call__
[rank1]:     video = self.vae.decode(latents, return_dict=False)[0]
[rank1]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
[rank1]:     return method(self, *args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 948, in decode
[rank1]:     decoded = self._decode(z).sample
[rank1]:               ^^^^^^^^^^^^^^^
[rank1]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 916, in _decode
[rank1]:     return self._temporal_tiled_decode(z, return_dict=return_dict)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 1135, in _temporal_tiled_decode
[rank1]:     decoded = self.decoder(tile)
[rank1]:               ^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 694, in forward
[rank1]:     hidden_states = up_block(hidden_states)
[rank1]:                     ^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 452, in forward
[rank1]:     hidden_states = upsampler(hidden_states)
[rank1]:                     ^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 115, in forward
[rank1]:     other_frames = F.interpolate(other_frames, scale_factor=self.upsample_factor, mode="nearest")
[rank1]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/functional.py", line 4538, in interpolate
[rank1]:     return torch._C._nn.upsample_nearest3d(input, output_size, scale_factors)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]: RuntimeError: upsample_nearest3d only supports output tensors with less than INT_MAX elements, but got [1, 256, 16, 720, 1280]
[rank3]: Traceback (most recent call last):
[rank3]:   File "/workspaces/cog-hunyuanvideo-multigpu/hunyuan_compile.py", line 46, in <module>
[rank3]:     output = pipe(
[rank3]:              ^^^^^
[rank3]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/para_attn/context_parallel/diffusers_adapters/hunyuan_video.py", line 204, in new_call
[rank3]:     return original_call(self, *args, generator=generator, **kwargs)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank3]:     return func(*args, **kwargs)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/pipelines/hunyuan_video/pipeline_hunyuan_video.py", line 676, in __call__
[rank3]:     video = self.vae.decode(latents, return_dict=False)[0]
[rank3]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
[rank3]:     return method(self, *args, **kwargs)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 948, in decode
[rank3]:     decoded = self._decode(z).sample
[rank3]:               ^^^^^^^^^^^^^^^
[rank3]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 916, in _decode
[rank3]:     return self._temporal_tiled_decode(z, return_dict=return_dict)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 1135, in _temporal_tiled_decode
[rank3]:     decoded = self.decoder(tile)
[rank3]:               ^^^^^^^^^^^^^^^^^^
[rank3]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank3]:     return self._call_impl(*args, **kwargs)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank3]:     return forward_call(*args, **kwargs)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 694, in forward
[rank3]:     hidden_states = up_block(hidden_states)
[rank3]:                     ^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank3]:     return self._call_impl(*args, **kwargs)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank3]:     return forward_call(*args, **kwargs)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 452, in forward
[rank3]:     hidden_states = upsampler(hidden_states)
[rank3]:                     ^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank3]:     return self._call_impl(*args, **kwargs)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank3]:     return forward_call(*args, **kwargs)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 115, in forward
[rank3]:     other_frames = F.interpolate(other_frames, scale_factor=self.upsample_factor, mode="nearest")
[rank3]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/functional.py", line 4538, in interpolate
[rank3]:     return torch._C._nn.upsample_nearest3d(input, output_size, scale_factors)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]: RuntimeError: upsample_nearest3d only supports output tensors with less than INT_MAX elements, but got [1, 256, 16, 720, 1280]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/workspaces/cog-hunyuanvideo-multigpu/hunyuan_compile.py", line 46, in <module>
[rank0]:     output = pipe(
[rank0]:              ^^^^^
[rank0]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/para_attn/context_parallel/diffusers_adapters/hunyuan_video.py", line 204, in new_call
[rank0]:     return original_call(self, *args, generator=generator, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/pipelines/hunyuan_video/pipeline_hunyuan_video.py", line 676, in __call__
[rank0]:     video = self.vae.decode(latents, return_dict=False)[0]
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
[rank0]:     return method(self, *args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 948, in decode
[rank0]:     decoded = self._decode(z).sample
[rank0]:               ^^^^^^^^^^^^^^^
[rank0]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 916, in _decode
[rank0]:     return self._temporal_tiled_decode(z, return_dict=return_dict)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 1135, in _temporal_tiled_decode
[rank0]:     decoded = self.decoder(tile)
[rank0]:               ^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 694, in forward
[rank0]:     hidden_states = up_block(hidden_states)
[rank0]:                     ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 452, in forward
[rank0]:     hidden_states = upsampler(hidden_states)
[rank0]:                     ^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 115, in forward
[rank0]:     other_frames = F.interpolate(other_frames, scale_factor=self.upsample_factor, mode="nearest")
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/functional.py", line 4538, in interpolate
[rank0]:     return torch._C._nn.upsample_nearest3d(input, output_size, scale_factors)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: upsample_nearest3d only supports output tensors with less than INT_MAX elements, but got [1, 256, 16, 720, 1280]
[rank2]: Traceback (most recent call last):
[rank2]:   File "/workspaces/cog-hunyuanvideo-multigpu/hunyuan_compile.py", line 46, in <module>
[rank2]:     output = pipe(
[rank2]:              ^^^^^
[rank2]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/para_attn/context_parallel/diffusers_adapters/hunyuan_video.py", line 204, in new_call
[rank2]:     return original_call(self, *args, generator=generator, **kwargs)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank2]:     return func(*args, **kwargs)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/pipelines/hunyuan_video/pipeline_hunyuan_video.py", line 676, in __call__
[rank2]:     video = self.vae.decode(latents, return_dict=False)[0]
[rank2]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
[rank2]:     return method(self, *args, **kwargs)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 948, in decode
[rank2]:     decoded = self._decode(z).sample
[rank2]:               ^^^^^^^^^^^^^^^
[rank2]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 916, in _decode
[rank2]:     return self._temporal_tiled_decode(z, return_dict=return_dict)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 1135, in _temporal_tiled_decode
[rank2]:     decoded = self.decoder(tile)
[rank2]:               ^^^^^^^^^^^^^^^^^^
[rank2]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank2]:     return forward_call(*args, **kwargs)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 694, in forward
[rank2]:     hidden_states = up_block(hidden_states)
[rank2]:                     ^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank2]:     return forward_call(*args, **kwargs)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 452, in forward
[rank2]:     hidden_states = upsampler(hidden_states)
[rank2]:                     ^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank2]:     return forward_call(*args, **kwargs)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py", line 115, in forward
[rank2]:     other_frames = F.interpolate(other_frames, scale_factor=self.upsample_factor, mode="nearest")
[rank2]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/root/.pyenv/versions/3.11.11/lib/python3.11/site-packages/torch/nn/functional.py", line 4538, in interpolate
[rank2]:     return torch._C._nn.upsample_nearest3d(input, output_size, scale_factors)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]: RuntimeError: upsample_nearest3d only supports output tensors with less than INT_MAX elements, but got [1, 256, 16, 720, 1280]
[rank1]:[W129 01:39:05.050890636 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
[rank3]:[W129 01:39:05.053554664 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
[rank2]:[W129 01:39:05.058658795 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
[rank0]:[W129 01:39:05.082491199 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
W0129 01:39:08.416000 84694 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 84769 closing signal SIGTERM
W0129 01:39:08.419000 84694 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 84770 closing signal SIGTERM
W0129 01:39:08.419000 84694 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 84772 closing signal SIGTERM
```

## Summary of the problem:
It seems like there are two problems:

1. `torch._dynamo hit config.cache_size_limit (8)` dynamo is hitting the cache size limit for number of recompiles, see [here](https://pytorch.org/docs/stable/torch.compiler_faq.html#why-is-compilation-slow), this is not fatal but results in compiler ignoring this problematic part of the graph (?)
2. `RuntimeError: upsample_nearest3d only supports output tensors with less than INT_MAX elements, but got [1, 256, 16, 720, 1280]` this one happens during 

does anyone have suggestions for approaches to debugging?

**Comment by chengzeyi** [comment]
Hey, Alex! I see some potential causes of the 2 problems.

First, since such high resolution is used, it is expected that the latent space tensor could be very large, and becomes beyond the capability of some torch kernels that uses int32 indexing.
So solve such problem, `pipe.enable_vae_tiling()` should be called, or `parallelize_vae()`, which alse calls `enable_vae_tileing()` under the hood, should be called, too. I guess you just missed to call `parallelize_vae()`

Another problem is hitting the cache size limit, which should be caused by failure of the obj id checks since `diffusers` instantiates new `attn_processor` for every transformer block, even they are identical under the hood. However, if the whole forward graph does not get split too aggressively, this shouldn't happen.
Since `torch.compile` works on the function call level, I decide to wrap calls of all the transformer blocks into a single `call_transformer_blocks` function call I can avoid the too many graph greaks issue. I have just fixed this issue in the latest version of `ParaAttention`. Try it and see if it really works!

Besides, `torch.backends.cuda.enable_cudnn_sdp(False)` might be unnecessary now, you could try removing it and see if it works now.

**Comment by alexarmbr** [comment]
thanks @chengzeyi!! this is fixed with latest commit
